name: Ethan Bot

on:
 schedule:
   - cron: '0 * * * *'
 workflow_dispatch:

jobs:
 send-message:
   runs-on: ubuntu-latest
   steps:
     - name: Check and notify
       env:
         SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
         SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
         BARK_KEY: ${{ secrets.BARK_KEY }}
       run: |
         python3 -
